import mysql from 'mysql2/promise';import bcrypt from 'bcryptjs';import dotenv from 'dotenv';
dotenv.config();
const database=process.env.DB_NAME||'usof';const base={host:process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||''};
const connection=await mysql.createConnection(base);
try{
  await connection.query(`CREATE DATABASE IF NOT EXISTS \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);await connection.query(`USE \`${database}\``);
  await connection.query('SET FOREIGN_KEY_CHECKS=0');
  for(const t of ['reactions','comments','post_categories','posts','categories','users']) await connection.query(`DROP TABLE IF EXISTS ${t}`);
  await connection.query('SET FOREIGN_KEY_CHECKS=1');
  await connection.query(`CREATE TABLE users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,login VARCHAR(50) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,full_name VARCHAR(100) NOT NULL DEFAULT '',email VARCHAR(190) NOT NULL UNIQUE,email_verified BOOLEAN NOT NULL DEFAULT 0,verification_token VARCHAR(100) NULL UNIQUE,avatar VARCHAR(255) NULL,rating INT NOT NULL DEFAULT 0,role ENUM('user','admin') NOT NULL DEFAULT 'user',reset_token_hash CHAR(64) NULL,reset_token_expires DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
  await connection.query(`CREATE TABLE categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(100) NOT NULL UNIQUE,description TEXT NOT NULL)`);
  await connection.query(`CREATE TABLE posts(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,author_id INT UNSIGNED NOT NULL,title VARCHAR(180) NOT NULL,content TEXT NOT NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',locked BOOLEAN NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_posts_created(created_at),INDEX idx_posts_status(status))`);
  await connection.query(`CREATE TABLE post_categories(post_id INT UNSIGNED NOT NULL,category_id INT UNSIGNED NOT NULL,PRIMARY KEY(post_id,category_id),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE)`);
  await connection.query(`CREATE TABLE comments(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id INT UNSIGNED NOT NULL,author_id INT UNSIGNED NOT NULL,parent_comment_id INT UNSIGNED NULL,content TEXT NOT NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',locked BOOLEAN NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE,INDEX idx_comments_post(post_id))`);
  await connection.query(`CREATE TABLE reactions(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,author_id INT UNSIGNED NOT NULL,post_id INT UNSIGNED NULL,comment_id INT UNSIGNED NULL,type ENUM('like','dislike') NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(comment_id) REFERENCES comments(id) ON DELETE CASCADE,CONSTRAINT chk_one_target CHECK ((post_id IS NOT NULL)+(comment_id IS NOT NULL)=1),UNIQUE KEY uniq_user_post(author_id,post_id),UNIQUE KEY uniq_user_comment(author_id,comment_id))`);
  const hash=await bcrypt.hash('Password123!',12); const users=[['admin','Admin User','admin@usof.local','admin'],['asya','Asya V','asya@usof.local','user'],['alex','Alex Kim','alex@usof.local','user'],['maria','Maria Dev','maria@usof.local','user'],['sam','Sam Code','sam@usof.local','user']];
  for(const u of users) await connection.query('INSERT INTO users(login,password_hash,full_name,email,email_verified,role) VALUES(?,?,?, ?,1,?)',[u[0],hash,u[1],u[2],u[3]]);
  const cats=[['JavaScript','JavaScript language and ecosystem'],['Node.js','Server-side JavaScript'],['React','React UI development'],['MySQL','Relational database questions'],['CSS','Layouts and styling'],['Git','Version control']]; for(const c of cats) await connection.query('INSERT INTO categories(title,description) VALUES(?,?)',c);
  for(let i=1;i<=6;i++){const [r]=await connection.query('INSERT INTO posts(author_id,title,content,status) VALUES(?,?,?,?)',[(i%4)+2,`Sample question ${i}`,`This is seeded Usof question number ${i}. Replace it by using the API.`,i===6?'inactive':'active']);await connection.query('INSERT INTO post_categories(post_id,category_id) VALUES(?,?),(?,?)',[r.insertId,(i%6)+1,r.insertId,((i+1)%6)+1]);}
  for(let i=1;i<=6;i++) await connection.query('INSERT INTO comments(post_id,author_id,parent_comment_id,content,status) VALUES(?,?,?,?,\'active\')',[((i-1)%5)+1,((i+1)%4)+2,i>3?i-3:null,`Seed comment ${i}`]);
  const reactions=[[2,1,null,'like'],[3,1,null,'like'],[4,2,null,'dislike'],[5,2,null,'like'],[2,null,1,'like'],[3,null,2,'dislike']]; for(const r of reactions) await connection.query('INSERT INTO reactions(author_id,post_id,comment_id,type) VALUES(?,?,?,?)',r);
  console.log(`Database ${database} initialized with seed data.`);
} finally {await connection.end();}
