import { pool } from '../config/db.js';
import { AppError } from '../utils/AppError.js';
import { setReaction, deleteReaction } from '../services/reactionService.js';

async function findComment(id){const [r]=await pool.execute('SELECT * FROM comments WHERE id=?',[id]);if(!r[0])throw new AppError(404,'COMMENT_NOT_FOUND','Comment not found');return r[0];}
export async function listPostComments(req,res){const [rows]=await pool.execute(`SELECT c.*,u.login author_login,COALESCE(SUM(CASE r.type WHEN 'like' THEN 1 WHEN 'dislike' THEN -1 ELSE 0 END),0) score FROM comments c JOIN users u ON u.id=c.author_id LEFT JOIN reactions r ON r.comment_id=c.id WHERE c.post_id=? AND (c.status='active' OR c.author_id=? OR ?='admin') GROUP BY c.id ORDER BY score ASC,c.created_at ASC`,[req.params.post_id,Number(req.user?.sub||0),req.user?.role||'guest']);res.json({data:rows});}
export async function createComment(req,res){if(!req.body.content?.trim())throw new AppError(422,'VALIDATION_ERROR','content is required');const [posts]=await pool.execute("SELECT id,status FROM posts WHERE id=?",[req.params.post_id]);if(!posts[0]||posts[0].status!=='active')throw new AppError(404,'POST_NOT_AVAILABLE','Active post not found');let parent=null;if(req.body.parentCommentId){parent=await findComment(req.body.parentCommentId);if(parent.post_id!==Number(req.params.post_id))throw new AppError(422,'INVALID_PARENT','Parent comment belongs to another post');}const [r]=await pool.execute('INSERT INTO comments(post_id,author_id,parent_comment_id,content,status) VALUES(?,?,?,?,\'active\')',[req.params.post_id,req.user.sub,parent?.id||null,req.body.content.trim()]);res.status(201).json({data:await findComment(r.insertId)});}
export async function getComment(req,res){res.json({data:await findComment(req.params.comment_id)});}
export async function updateComment(req,res){const c=await findComment(req.params.comment_id);if(req.user.role!=='admin'&&Number(req.user.sub)!==c.author_id)throw new AppError(403,'FORBIDDEN','Cannot update this comment');const status=req.body.status??c.status;if(!['active','inactive'].includes(status))throw new AppError(422,'INVALID_STATUS','Invalid status');await pool.execute('UPDATE comments SET status=? WHERE id=?',[status,c.id]);res.json({data:await findComment(c.id)});}
export async function deleteComment(req,res){const c=await findComment(req.params.comment_id);if(req.user.role!=='admin'&&Number(req.user.sub)!==c.author_id)throw new AppError(403,'FORBIDDEN','Cannot delete this comment');await pool.execute('DELETE FROM comments WHERE id=?',[c.id]);res.status(204).end();}
export async function getCommentReactions(req,res){await findComment(req.params.comment_id);const [rows]=await pool.execute('SELECT id,author_id,type,created_at FROM reactions WHERE comment_id=?',[req.params.comment_id]);res.json({data:rows});}
export async function reactToComment(req,res){await findComment(req.params.comment_id);await setReaction({userId:Number(req.user.sub),commentId:Number(req.params.comment_id),type:req.body.type});res.json({message:'Reaction saved'});}
export async function removeCommentReaction(req,res){await deleteReaction({userId:Number(req.user.sub),commentId:Number(req.params.comment_id),isAdmin:req.user.role==='admin'&&req.query.all==='1'});res.status(204).end();}
