import { pool } from '../config/db.js';
import { AppError } from '../utils/AppError.js';
import { setReaction, deleteReaction } from '../services/reactionService.js';

const allowedSort = { likes: 'score', date: 'p.created_at' };
function normalizeCategories(value) { if (!Array.isArray(value) || value.length === 0) throw new AppError(422, 'CATEGORIES_REQUIRED', 'At least one category is required'); return [...new Set(value.map(Number).filter(Number.isInteger))]; }
async function getPostById(id, user) { const [rows] = await pool.execute(`SELECT p.*, u.login author_login, COALESCE(SUM(CASE r.type WHEN 'like' THEN 1 WHEN 'dislike' THEN -1 ELSE 0 END),0) score FROM posts p JOIN users u ON u.id=p.author_id LEFT JOIN reactions r ON r.post_id=p.id WHERE p.id=? GROUP BY p.id`, [id]); const post = rows[0]; if (!post) throw new AppError(404, 'POST_NOT_FOUND', 'Post not found'); const isOwner = user && Number(user.sub) === post.author_id; if (post.status === 'inactive' && user?.role !== 'admin' && !isOwner) throw new AppError(404, 'POST_NOT_FOUND', 'Post not found'); const [categories] = await pool.execute('SELECT c.* FROM categories c JOIN post_categories pc ON pc.category_id=c.id WHERE pc.post_id=?', [id]); return { ...post, categories }; }
export async function listPosts(req, res) { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 10)); const sort = allowedSort[req.query.sort] || 'score'; const order = String(req.query.order).toLowerCase() === 'asc' ? 'ASC' : 'DESC'; const where = []; const params = []; if (req.user?.role !== 'admin') { if (req.user) { where.push('(p.status=\'active\' OR p.author_id=?)'); params.push(Number(req.user.sub)); } else where.push('p.status=\'active\''); } if (req.query.status && req.user?.role === 'admin') { where.push('p.status=?'); params.push(req.query.status); } if (req.query.from) { where.push('p.created_at>=?'); params.push(req.query.from); } if (req.query.to) { where.push('p.created_at<=?'); params.push(req.query.to); } if (req.query.category) { where.push('EXISTS(SELECT 1 FROM post_categories fpc WHERE fpc.post_id=p.id AND fpc.category_id=?)'); params.push(Number(req.query.category)); } if (req.query.search) { where.push('(p.title LIKE ? OR p.content LIKE ?)'); const q=`%${req.query.search}%`; params.push(q,q); } const clause = where.length ? `WHERE ${where.join(' AND ')}` : ''; const [countRows] = await pool.execute(`SELECT COUNT(*) total FROM posts p ${clause}`, params); const [rows] = await pool.execute(`SELECT p.*, u.login author_login, COALESCE(SUM(CASE r.type WHEN 'like' THEN 1 WHEN 'dislike' THEN -1 ELSE 0 END),0) score FROM posts p JOIN users u ON u.id=p.author_id LEFT JOIN reactions r ON r.post_id=p.id ${clause} GROUP BY p.id ORDER BY ${sort} ${order} LIMIT ? OFFSET ?`, [...params, limit, (page-1)*limit]); res.json({ data: rows, pagination: { page, limit, total: countRows[0].total, totalPages: Math.ceil(countRows[0].total/limit) } }); }
export async function getPost(req,res){ res.json({ data: await getPostById(req.params.post_id, req.user) }); }
export async function createPost(req,res){ const { title, content }=req.body; const categories=normalizeCategories(req.body.categories); if(!title?.trim()||!content?.trim()) throw new AppError(422,'VALIDATION_ERROR','title and content are required'); const conn=await pool.getConnection(); try{ await conn.beginTransaction(); const [result]=await conn.query('INSERT INTO posts(author_id,title,content,status) VALUES(?,?,?,\'active\')',[req.user.sub,title.trim(),content.trim()]); for(const id of categories) await conn.query('INSERT INTO post_categories(post_id,category_id) VALUES(?,?)',[result.insertId,id]); await conn.commit(); res.status(201).json({data:await getPostById(result.insertId,req.user)}); }catch(e){await conn.rollback(); throw e;}finally{conn.release();} }
export async function updatePost(req,res){ const post=await getPostById(req.params.post_id,req.user); const isAdmin=req.user.role==='admin'; const isOwner=Number(req.user.sub)===post.author_id; if(!isAdmin&&!isOwner) throw new AppError(403,'FORBIDDEN','Only owner or admin can update this post'); const title=isAdmin?post.title:(req.body.title??post.title); const content=isAdmin?post.content:(req.body.content??post.content); const status=isAdmin?(req.body.status??post.status):post.status; if(!['active','inactive'].includes(status)) throw new AppError(422,'INVALID_STATUS','Invalid status'); await pool.execute('UPDATE posts SET title=?, content=?, status=? WHERE id=?',[title,content,status,post.id]); if(req.body.categories){ const cats=normalizeCategories(req.body.categories); await pool.execute('DELETE FROM post_categories WHERE post_id=?',[post.id]); for(const id of cats) await pool.execute('INSERT INTO post_categories(post_id,category_id) VALUES(?,?)',[post.id,id]); } res.json({data:await getPostById(post.id,req.user)}); }
export async function deletePost(req,res){ const post=await getPostById(req.params.post_id,req.user); if(req.user.role!=='admin'&&Number(req.user.sub)!==post.author_id) throw new AppError(403,'FORBIDDEN','Cannot delete this post'); await pool.execute('DELETE FROM posts WHERE id=?',[post.id]); res.status(204).end(); }
export async function getPostCategories(req,res){ const post=await getPostById(req.params.post_id,req.user); res.json({data:post.categories}); }
export async function getPostReactions(req,res){ await getPostById(req.params.post_id,req.user); const [rows]=await pool.execute('SELECT id,author_id,type,created_at FROM reactions WHERE post_id=?',[req.params.post_id]); res.json({data:rows}); }
export async function reactToPost(req,res){ await getPostById(req.params.post_id,req.user); await setReaction({userId:Number(req.user.sub),postId:Number(req.params.post_id),type:req.body.type}); res.json({message:'Reaction saved'}); }
export async function removePostReaction(req,res){ await deleteReaction({userId:Number(req.user.sub),postId:Number(req.params.post_id),isAdmin:req.user.role==='admin'&&req.query.all==='1'}); res.status(204).end(); }
