import bcrypt from 'bcryptjs';
import { pool } from '../config/db.js';
import { User } from '../models/User.js';
import { AppError } from '../utils/AppError.js';

export async function listUsers(req, res) { res.json({ data: await User.list() }); }
export async function getUser(req, res) { const user = await User.findById(req.params.user_id); if (!user) throw new AppError(404, 'USER_NOT_FOUND', 'User not found'); res.json({ data: user }); }
export async function createUser(req, res) { const { login, password, passwordConfirmation, email, role='user', fullName='' } = req.body; if (!login || !password || !email || password !== passwordConfirmation) throw new AppError(422, 'VALIDATION_ERROR', 'Invalid user data'); if (!['user','admin'].includes(role)) throw new AppError(422, 'INVALID_ROLE', 'Role must be user or admin'); const hash = await bcrypt.hash(password, 12); try { const [result] = await pool.execute('INSERT INTO users(login,password_hash,full_name,email,email_verified,role) VALUES(?,?,?,?,1,?)', [login, hash, fullName, email.toLowerCase(), role]); res.status(201).json({ data: await User.findById(result.insertId) }); } catch (error) { if (error.code === 'ER_DUP_ENTRY') throw new AppError(409, 'USER_EXISTS', 'Login or email is already used'); throw error; } }
export async function updateUser(req, res) { const id = Number(req.params.user_id); if (req.user.role !== 'admin' && Number(req.user.sub) !== id) throw new AppError(403, 'FORBIDDEN', 'You can update only your profile'); const current = await User.findById(id); if (!current) throw new AppError(404, 'USER_NOT_FOUND', 'User not found'); const fullName = req.body.fullName ?? current.full_name; const email = (req.body.email ?? current.email).toLowerCase(); const role = req.user.role === 'admin' ? (req.body.role ?? current.role) : current.role; if (!['user','admin'].includes(role)) throw new AppError(422, 'INVALID_ROLE', 'Invalid role'); await pool.execute('UPDATE users SET full_name=?, email=?, role=? WHERE id=?', [fullName, email, role, id]); res.json({ data: await User.findById(id) }); }
export async function uploadAvatar(req, res) { if (!req.file) throw new AppError(422, 'FILE_REQUIRED', 'Avatar file is required'); const avatar = `/uploads/avatars/${req.file.filename}`; await pool.execute('UPDATE users SET avatar=? WHERE id=?', [avatar, req.user.sub]); res.json({ data: await User.findById(req.user.sub) }); }
export async function deleteUser(req, res) { const id = Number(req.params.user_id); if (req.user.role !== 'admin' && Number(req.user.sub) !== id) throw new AppError(403, 'FORBIDDEN', 'You can delete only your profile'); const [result] = await pool.execute('DELETE FROM users WHERE id=?', [id]); if (!result.affectedRows) throw new AppError(404, 'USER_NOT_FOUND', 'User not found'); res.status(204).end(); }
